### ISSUE TITLE
頂点インデックスサイズが4以外で保存すると不正ファイルとなる

### ISSUE THREAD

**Issue by flammpfeil** [zyando/MMDataIO#3]
面の頂点インデックスの保存値に頂点インデックスサイズが反映されていません
https://github.com/zyando/MMDataIO/blob/ce8a7be2dc86b21f8669f72e921a196814bb4394/MMDataIO/Pmx/PmxModelData.cs#L38
`WriteData(VertexIndices, (i, ex) => ex.WritePmxId(Header.VertexIndexSize,i), writer);`

**Comment by dojadon** [comment]
修正しました。
